# Default values for helm-todo-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: sohail/todo-web
  tag: latest
  pullPolicy: Always
service:
  name: web
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: true
  # Used to create Ingress record (should used with service.type: ClusterIP).
  host: todoapp.local
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    - secretName: ingress-tls-secret
      hosts:
        - todoapp.local
resources: {}
