# Default values for todo-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
image:
  repository: sohail/todo-api
  tag: latest
  pullPolicy: Always
service:
  name: api
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000
ingress:
  enabled: false
resources: {}
